version: "3.9"

services:
  backend:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: infra/Dockerfile
    volumes:
      - static-volume:/app/src/static/
      - ..:/app
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=src.core.settings.prod
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/app/src/static
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  static-volume:
