# Generated by Django 4.2.7 on 2024-08-22 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("title", models.CharField(max_length=255, verbose_name="시험 제목")),
                ("description", models.TextField(verbose_name="시험 내용")),
                ("max_capacity", models.PositiveIntegerField(default=50000, verbose_name="최대 시험 응시 가능 고객수")),
                ("current_capacity", models.PositiveIntegerField(default=0, verbose_name="현재 시험 신청 고객수")),
                ("reservation_started_at", models.DateTimeField(verbose_name="예약 시작 시간")),
                ("reservation_ended_at", models.DateTimeField(verbose_name="예약 종료 시간")),
                ("started_at", models.DateTimeField(verbose_name="시험 시작 시간")),
                ("ended_at", models.DateTimeField(verbose_name="시험 종료 시간")),
            ],
            options={
                "verbose_name": "시험",
                "verbose_name_plural": "시험",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "PENDING"), ("CANCELED", "CANCELED"), ("CONFIRM", "CONFIRM")],
                        max_length=10,
                        verbose_name="예약 상태",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reservations", to="reservations.exam"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "예약",
                "verbose_name_plural": "예약",
                "ordering": ["-pk"],
            },
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["title"], name="idx_title"),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["status"], name="idx_status"),
        ),
    ]
