# Generated by Django 4.2.7 on 2024-08-23 11:52

from django.conf import settings
from django.db import migrations, models
import src.core.enums.reservation


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="users",
            field=models.ManyToManyField(
                related_name="exams", through="reservations.Reservation", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "PENDING"), ("CANCELED", "CANCELED"), ("CONFIRM", "CONFIRM")],
                default=src.core.enums.reservation.ReservationStatusEnum["PENDING"],
                max_length=10,
                verbose_name="예약 상태",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["user", "exam"], name="idx_user_exam"),
        ),
    ]
