# Generated by Django 4.2.7 on 2024-08-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_exam_users_alter_reservation_status_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(fields=("user", "exam"), name="unique_user_exam"),
        ),
    ]
