# Generated by Django 4.2.7 on 2024-08-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_unique_user_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CANCELED', 'CANCELED'), ('CONFIRM', 'CONFIRM')], default='PENDING', max_length=10, verbose_name='예약 상태'),
        ),
    ]
