# Generated by Django 4.2.7 on 2024-08-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_alter_reservation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="number_of_applicants",
            field=models.PositiveIntegerField(default=1, verbose_name="응시생 수"),
            preserve_default=False,
        ),
    ]
